### ISSUE TITLE
Move configuration data from model.py

### ISSUE THREAD

**Issue by ekondrashev** [shmuta/pybbs#1]
There is a data in model.py that should be replaced to *.properties configuration file, for now it is choices data.
The problem is that 'root' message should be available as global variable as name or as Message.
Perhaps we need to create a Config class to keep such a data. Lets disscuss.

**Comment by shmuta** [comment]
Could you provide some example how it will look like and more explanation?

**Comment by ekondrashev** [comment]
'root' message is not needed any more, root message is that one that has no parent.
Choices data should not be regulated.
So issue is not relevant for now.

**Comment by shmuta** [comment]
What about choices data?

**Comment by shmuta** [comment]
Fixed in http://github.com/shmuta/pybbs/commit/8fcc464130058db241aa163cadb8df79e202c309
