### ISSUE TITLE
ManyToMany relationship 

### ISSUE THREAD

**Issue by shmuta** [shmuta/pybbs#2]
Create ManyToMany relationship between Message objects according to requirements.

**Comment by shmuta** [comment]
Fixed in http://github.com/shmuta/pybbs/commit/8d709d123765f90a0567703950da2947caec1476 commit

**Comment by shmuta** [comment]
Improvements in http://github.com/shmuta/pybbs/commit/1ad6e939352df7386459fbd1ffc2bca4b1cb2836

**Comment by ekondrashev** [comment]
Verified.
