### ISSUE TITLE
Remove choice data, add initialization script for choice data

### ISSUE THREAD

**Issue by ekondrashev** [shmuta/pybbs#5]
Remove choice data from models.py, add initialization script for choice data

**Comment by shmuta** [comment]
After commit http://github.com/shmuta/pybbs/commit/048a685d50091da8f4606ac80978096792b923da it works well for me. Thanks!

**Comment by ekondrashev** [comment]
Added initialisation of db for other then sqlite db engine.
http://github.com/shmuta/pybbs/commit/048a685d50091da8f4606ac80978096792b923da
Please review and close issue if there are no problems with this.
